"""Add Quantity field to BillDetails

Revision ID: 5db645305235
Revises: 
Create Date: 2025-02-16 16:34:58.420723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db645305235'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Quantity', sa.Integer(), nullable=False))

    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.alter_column('Billing_ID',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_foreign_key(None, 'user', ['Client_ID'], ['id'])
        batch_op.create_foreign_key(None, 'hst', ['HST_ID'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('Billing_ID',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('bill_details', schema=None) as batch_op:
        batch_op.drop_column('Quantity')

    # ### end Alembic commands ###
